name: Build Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create public directory if it doesn't exist
      run: |
        if (!(Test-Path -Path "public")) {
          New-Item -ItemType Directory -Path "public"
          Copy-Item -Path "index.html" -Destination "public/"
        }

    - name: Build executable
      run: npm run build

    - name: Create release zip
      run: npm run compress

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CaptionAI
        path: dist/CaptionAI.exe

    - name: Upload zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: CaptionAI-release
        path: dist/CaptionAI-release.zip
